# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d51e4f8195ee4418e3c0ab9bf4343e2d55df4f4058e3c32788840c040c28e9cba334e0131eda7f97369521eda2c0a278650976b3814621195d769d8129ef407

test:
  secret_key_base: f3438846a7944e4377bfdccf1fa9e6e0c492e9c30e457dc3e9bc19054bf3632e0a2e90a82528caff356104719f3eff2c7f8f64660baf01f43866f154c4d3d64b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
